'use client';
import { FormEvent, useEffect, useState } from 'react';
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
type Job = { id: number; company: string; title: string; pay: string; remote?: boolean };
type Screen = 'jobs' | 'account' | 'details' | 'success';
export default function Home() {
  const [screen, setScreen] = useState<Screen>('jobs'); const [jobs, setJobs] = useState<Job[]>([]); const [selectedJob, setSelectedJob] = useState<number | null>(null); const [token, setToken] = useState(''); const [error, setError] = useState(''); const [showPassword, setShowPassword] = useState(false);
  useEffect(() => { fetch("/api/jobs").then((response) => response.json()).then((result) => setJobs(result.jobs)).catch(() => setError('Unable to load roles right now.')); }, []);
  const go = (next: Screen) => { setScreen(next); window.scrollTo(0, 0); setError(''); };
  async function register(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`${API_URL}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) return setError(result.message || result.error || 'Unable to create your account.'); setToken(result.token); go('details'); }
  async function submitApplication(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const body = new FormData(event.currentTarget); body.append('jobId', String(selectedJob || 1)); const response = await fetch(`${API_URL}/applications`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body }); const result = await response.json(); if (!response.ok) return setError(result.message || result.error || 'Unable to submit your application.'); go('success'); }
  return <div className="site-shell"><header className="topbar"><button className="brand" onClick={() => go('jobs')} aria-label="VirexaTech jobs"><span className="brand-mark">V</span><span>virexa<span>tech</span></span></button><div className="header-note"><span className="status-dot" /> Applications open</div></header><main>
    {screen === 'jobs' && <section className="screen screen-jobs"><div className="jobs-intro"><div><p className="eyebrow">Your next move starts here</p><h1>Work that moves<br /><em>you forward.</em></h1><p className="intro-copy">Find flexible roles with trusted global teams. Choose an opportunity and take the first step today.</p></div><div className="intro-stamp"><strong>{String(jobs.length).padStart(2, '0')}</strong><span>open roles<br />right now</span></div></div><div className="job-list" aria-live="polite">{jobs.map((job) => <article className="job-card" key={job.id}><div className="job-company">{job.company}<small>Verified employer</small></div><div className="job-title">{job.title}</div><div className="job-pay">{job.pay}</div><div className="job-location">{job.remote ? 'Remote' : 'Flexible'}</div><button className="primary-button" onClick={() => { setSelectedJob(job.id); go('account'); }}>Apply now <span>→</span></button></article>)}</div>{error && <p className="form-message error">{error}</p>}</section>}
    {screen === 'account' && <section className="screen form-screen"><button className="back-button" onClick={() => go('jobs')}>← Back to roles</button><div className="form-layout"><Aside step="01 / 02" title={<>Make it<br /><em>official.</em></>} text="Your details stay private and are only used to process your application." label="Account details" /><form className="application-form" onSubmit={register}><FormHeading title="Let’s get to know you." eyebrow="Create your account" copy="Set up your secure applicant profile to continue." /><div className="field-grid"><label>Full name<input name="fullName" placeholder="Alex Morgan" required /></label><label>Email address<input name="email" type="email" placeholder="alex@email.com" required /></label><label>Password<div className="password-field"><input name="password" type={showPassword ? 'text' : 'password'} placeholder="At least 8 characters" minLength={8} required /><button type="button" className="password-toggle" onClick={() => setShowPassword((current) => !current)}>{showPassword ? 'Hide' : 'Show'}</button></div></label><label className="full-field">Confirm password<div className="password-field"><input name="confirmPassword" type={showPassword ? 'text' : 'password'} placeholder="Repeat your password" minLength={8} required /><button type="button" className="password-toggle" onClick={() => setShowPassword((current) => !current)}>{showPassword ? 'Hide' : 'Show'}</button></div></label></div><p className="form-message error">{error}</p><button className="primary-button" type="submit">Continue to details <span>→</span></button></form></div></section>}
    {screen === 'details' && <section className="screen form-screen"><button className="back-button" onClick={() => go('jobs')}>← View other roles</button><div className="form-layout"><Aside step="02 / 02" title={<>Bring your<br /><em>whole self.</em></>} text="A complete profile helps the right team see your potential." label="Profile & verification" complete /><form className="application-form" onSubmit={submitApplication} encType="multipart/form-data"><FormHeading title="Almost there." eyebrow="Upload your details" copy="Add the documents needed to complete your application." /><label>Mailing address<textarea name="address" rows={3} placeholder="Street, city, state, country" required /></label><div className="upload-grid"><Upload name="cv" title="CV" accept=".pdf,.jpg,.jpeg,.png" /><Upload name="resume" title="Resume" accept=".pdf,.jpg,.jpeg,.png" /><Upload name="governmentId" title="Government ID" accept=".jpg,.jpeg,.png,.pdf" /><Upload name="video" title="Video verification" accept="video/mp4,video/webm,video/quicktime" video /></div><p className="form-message error">{error}</p><button className="primary-button" type="submit">Submit application <span>→</span></button></form></div></section>}
    {screen === 'success' && <section className="screen success-screen"><div className="success-mark">✓</div><p className="eyebrow">Application received</p><h2>You’re on your<br /><em>way forward.</em></h2><p>Your application is safely with our team. We’ll be in touch if your experience is a match.</p><button className="primary-button" onClick={() => go('jobs')}>Browse other roles <span>→</span></button></section>}
  </main><footer><span>© 2026 VirexaTech</span><span>Work with purpose.</span></footer></div>;
}
function Aside({ step, title, text, label, complete = false }: { step: string; title: React.ReactNode; text: string; label: string; complete?: boolean }) { return <div className="form-aside"><p className="eyebrow">Step {step}</p><h2>{title}</h2><p>{text}</p><div className="progress-line"><span className={complete ? 'complete' : ''} /></div><small>{label}</small></div>; }
function FormHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="form-heading"><p className="eyebrow">{eyebrow}</p><h3>{title}</h3><p>{copy}</p></div>; }
function Upload({ name, title, accept, video = false }: { name: string; title: string; accept: string; video?: boolean }) { return <label className="upload-box"><span className="upload-icon">{video ? '◉' : '↑'}</span><strong>{title}</strong><small>{video ? 'MP4, MOV or WEBM' : 'PDF, JPG or PNG'} · 20MB max</small><input name={name} type="file" accept={accept} required /></label>; }
